### ISSUE TITLE
iOS13-debugserver_arm64e不好使

### ISSUE THREAD

**Issue by nenseso** [wstclzy2010/iOS-debugserver#1]
环境：iPhone6s，iOS 13.4.1
root执行 debugserver *:10011 -a 14566
报错：-sh: /usr/bin/debugserver: Bad CPU type in executable
换了iOS12的arm64架构的debugserver后，好使

另外想问一下大佬：
我一开始把/Developer/usr/debuserver目录下的debugserver导出来，想自己签名权限的，但是查看文件类型，不是mach-o格式的，是data类型的,导致根本执行不了，有办法把它转成mach-o格式吗？

**Comment by wstclzy2010** [comment]
> iPhone6s，iOS 13.4.1 iOS13-debugserver_arm64e不好使
>
肯定的，a9是arm64不是arm64e

> 不是mach-o格式的，是data类型的
>
你应该不是通过scp命令复制出来，而是用某些工具导出的，会权限异常
```
chmod +x debugserver
```
后变成正常的可执行文件了

**Comment by nenseso** [comment]
> 你应该不是通过scp命令复制出来，而是用某些工具导出的，会权限异常

谢谢大佬指点，这样做导出来的确实好使，是mach-o的可执行文件，我之前一直用ifunbox导出的，导出来的都是data文件，还一直纳闷是不是iOS 13的问题。
